version: '3.2'

services:
    db:
        image: postgres:13.1
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
        networks:
            - app

    php: &app-service
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/app:cached
            - /etc/timezone:/etc/timezone:cached
        environment:
            APP_ENV: dev
            APP_URL: http://localhost:8000
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: app
            DB_USERNAME: user
            DB_PASSWORD: secret
            QUEUE_CONNECTION: redis
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_CLIENT: predis
            THUMB_SIZE_WIDTH: 200
            THUMB_SIZE_HEIGHT: 400
        networks:
            - app

    queue:
        <<: *app-service
        user: "www-data"
        restart: always
        command: 'php artisan queue:listen --memory=64'
        networks:
            - app

    nginx:
        image: nginx:1.16.0-alpine
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www/app:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        networks:
            - app

    redis:
        image: redis:4.0.11-alpine
        restart: always
        command: redis-server
        volumes:
            - redis-data:/data:cached
        ports: 
            - 16379:6379
        networks:
            - app

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app

    node:
        user: "node"
        image: node:14.7.0-alpine
        volumes:
            - ./:/var/www/app:cached
        working_dir: /var/www/app

networks:
    app:
        driver: bridge

volumes:
    db-data:
    redis-data: