version: '3'

services:
    db:
        container_name: db
        image: postgres:13.1
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
        networks:
            - app

    php:
        container_name: php
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/app:cached
            - /etc/timezone:/etc/timezone:cached
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: app
            DB_USERNAME: user
            DB_PASSWORD: secret
        networks:
            - app

    nginx:
        container_name: nginx
        image: nginx:1.16.0-alpine
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www/app:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        networks:
            - app

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app

    composer:
        image: composer:1.9.3
        volumes:
            - ./:/var/www/app:cached
        working_dir: /var/www/app

networks:
    app:
        driver: bridge

volumes:
    db-data: